name: persistent-mtl
version: 0.2.2.0
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
synopsis: Monad transformer for the persistent API
description: |
  A monad transformer and mtl-style type class for using the
  persistent API directly in your monad transformer stack.
category: Database
license: BSD3
extra-source-files:
  - CHANGELOG.md
  - README.md
  - test/goldens/**/*.golden

ghc-options: -Wall

github: brandonchinn178/persistent-mtl

library:
  source-dirs: src
  dependencies:
    - base >= 4.10 && < 4.16
    - conduit >= 1.3.0.3 && < 1.4
    - containers >= 0.5.10.2 && < 0.7
    - mtl >= 2.2.2 && < 2.3
    - persistent >= 2.8.2 && < 2.14
    - resource-pool >= 0.2.3.2 && < 0.3
    - resourcet >= 1.2.1 && < 1.3
    - text >= 1.2.3.0 && < 1.3
    - transformers >= 0.5.2.0 && < 0.6
    - unliftio >= 0.2.7.0 && < 0.3
    - unliftio-core >= 0.1.2.0 && < 0.3
    - unliftio-pool >= 0.2.0.0 && < 0.3

tests:
  persistent-mtl-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - conduit
      - containers
      - esqueleto
      - monad-logger
      - persistent
      - persistent-mtl
      - persistent-postgresql
      - persistent-sqlite
      - persistent-template
      - resource-pool
      - resourcet
      - tasty
      - tasty-golden
      - tasty-hunit
      - text
      - unliftio
