name: persistent-mtl
version: 0.1.0.0
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base >= 4.10 && < 5
    - mtl >= 2.2.2 && < 3
    - persistent >= 2.8.2 && < 3
    - resource-pool >= 0.2.3.2 && < 0.3
    - resourcet >= 1.2.1 && < 2
    - text >= 1.2.3.0 && < 2
    - unliftio-core >= 0.1.2.0 && < 0.3

tests:
  persistent-mtl-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - monad-logger
      - persistent
      - persistent-mtl
      - persistent-sqlite
      - persistent-template
      - tasty
      - tasty-hunit
      - unliftio
