{-|
Module: Database.Persist.Monad.Shim

Defines all the @persistent@ functions lifted into 'MonadSqlQuery', and
re-exports a version of the @Database.Persist.Sql@ module replacing each
function with the lifted version.

This file is autogenerated, to keep it in sync with
@Database.Persist.Monad.SqlQueryRep@.
-}

{- THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY -}

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE RankNTypes #-}

module Database.Persist.Monad.Shim (
  module Database.Persist.Sql,
  get,
  getMany,
  getJust,
  getJustEntity,
  getEntity,
  belongsTo,
  belongsToJust,
  insert,
  insert_,
  insertMany,
  insertMany_,
  insertEntityMany,
  insertKey,
  repsert,
  repsertMany,
  replace,
  delete,
  update,
  updateGet,
  insertEntity,
  insertRecord,
  getBy,
#if MIN_VERSION_persistent(2,10,0)
  getByValue,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  getByValue,
#endif
  checkUnique,
#if MIN_VERSION_persistent(2,11,0)
  checkUniqueUpdateable,
#endif
  deleteBy,
  insertUnique,
#if MIN_VERSION_persistent(2,10,0)
  upsert,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  upsert,
#endif
  upsertBy,
  putMany,
#if MIN_VERSION_persistent(2,10,0)
  insertBy,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  insertBy,
#endif
  insertUniqueEntity,
  replaceUnique,
#if MIN_VERSION_persistent(2,10,0)
  onlyUnique,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  onlyUnique,
#endif
  selectSourceRes,
  selectFirst,
  selectKeysRes,
  count,
#if MIN_VERSION_persistent(2,11,0)
  exists,
#endif
  selectSource,
  selectKeys,
  selectList,
  selectKeysList,
  updateWhere,
  deleteWhere,
  deleteWhereCount,
  updateWhereCount,
#if !MIN_VERSION_persistent(2,13,0)
  deleteCascade,
#endif
#if !MIN_VERSION_persistent(2,13,0)
  deleteCascadeWhere,
#endif
  parseMigration,
  parseMigration',
  printMigration,
  showMigration,
  getMigration,
  runMigration,
#if MIN_VERSION_persistent(2,10,2)
  runMigrationQuiet,
#endif
  runMigrationSilent,
  runMigrationUnsafe,
#if MIN_VERSION_persistent(2,10,2)
  runMigrationUnsafeQuiet,
#endif
  getFieldName,
  getTableName,
  withRawQuery,
  rawQueryRes,
  rawQuery,
  rawExecute,
  rawExecuteCount,
  rawSql,
  transactionSave,
#if MIN_VERSION_persistent(2,9,0)
  transactionSaveWithIsolation,
#endif
  transactionUndo,
#if MIN_VERSION_persistent(2,9,0)
  transactionUndoWithIsolation,
#endif
  unsafeLiftSql,
  ) where

import Control.Monad.IO.Class (MonadIO)
import Control.Monad.Trans.Class (lift)
import Control.Monad.Trans.Resource (MonadResource)
import Data.Acquire (Acquire, allocateAcquire)
import Data.Conduit (ConduitM)
import Data.Int (Int64)
import Data.Map (Map)
import Data.Text (Text)
import Data.Typeable (Typeable)
import Data.Void (Void)
import Database.Persist.Sql hiding (
  get,
  getMany,
  getJust,
  getJustEntity,
  getEntity,
  belongsTo,
  belongsToJust,
  insert,
  insert_,
  insertMany,
  insertMany_,
  insertEntityMany,
  insertKey,
  repsert,
  repsertMany,
  replace,
  delete,
  update,
  updateGet,
  insertEntity,
  insertRecord,
  getBy,
#if MIN_VERSION_persistent(2,10,0)
  getByValue,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  getByValue,
#endif
  checkUnique,
#if MIN_VERSION_persistent(2,11,0)
  checkUniqueUpdateable,
#endif
  deleteBy,
  insertUnique,
#if MIN_VERSION_persistent(2,10,0)
  upsert,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  upsert,
#endif
  upsertBy,
  putMany,
#if MIN_VERSION_persistent(2,10,0)
  insertBy,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  insertBy,
#endif
  insertUniqueEntity,
  replaceUnique,
#if MIN_VERSION_persistent(2,10,0)
  onlyUnique,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  onlyUnique,
#endif
  selectSourceRes,
  selectFirst,
  selectKeysRes,
  count,
#if MIN_VERSION_persistent(2,11,0)
  exists,
#endif
  selectSource,
  selectKeys,
  selectList,
  selectKeysList,
  updateWhere,
  deleteWhere,
  deleteWhereCount,
  updateWhereCount,
#if !MIN_VERSION_persistent(2,13,0)
  deleteCascade,
#endif
#if !MIN_VERSION_persistent(2,13,0)
  deleteCascadeWhere,
#endif
  parseMigration,
  parseMigration',
  printMigration,
  showMigration,
  getMigration,
  runMigration,
#if MIN_VERSION_persistent(2,10,2)
  runMigrationQuiet,
#endif
  runMigrationSilent,
  runMigrationUnsafe,
#if MIN_VERSION_persistent(2,10,2)
  runMigrationUnsafeQuiet,
#endif
  getFieldName,
  getTableName,
  withRawQuery,
  rawQueryRes,
  rawQuery,
  rawExecute,
  rawExecuteCount,
  rawSql,
  transactionSave,
#if MIN_VERSION_persistent(2,9,0)
  transactionSaveWithIsolation,
#endif
  transactionUndo,
#if MIN_VERSION_persistent(2,9,0)
  transactionUndoWithIsolation,
#endif
  pattern Update
  )
import GHC.Stack (HasCallStack)

import Database.Persist.Monad.Class (MonadSqlQuery, runCompatibleQueryRep)
import Database.Persist.Monad.SqlQueryRep (QueryRep(..))

{-# ANN module "HLint: ignore" #-}

-- | The lifted version of 'Database.Persist.Sql.get'
get
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> m (Maybe record)
get a1 = runCompatibleQueryRep $ Get a1

-- | The lifted version of 'Database.Persist.Sql.getMany'
getMany
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Key record] -> m (Map (Key record) record)
getMany a1 = runCompatibleQueryRep $ GetMany a1

-- | The lifted version of 'Database.Persist.Sql.getJust'
getJust
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> m record
getJust a1 = runCompatibleQueryRep $ GetJust a1

-- | The lifted version of 'Database.Persist.Sql.getJustEntity'
getJustEntity
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> m (Entity record)
getJustEntity a1 = runCompatibleQueryRep $ GetJustEntity a1

-- | The lifted version of 'Database.Persist.Sql.getEntity'
getEntity
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> m (Maybe (Entity record))
getEntity a1 = runCompatibleQueryRep $ GetEntity a1

-- | The lifted version of 'Database.Persist.Sql.belongsTo'
belongsTo
  :: (PersistEntity record1, PersistRecordBackend record2 SqlBackend, Typeable record1, Typeable record2, MonadSqlQuery m)
  => (record1 -> Maybe (Key record2)) -> record1 -> m (Maybe record2)
belongsTo a1 a2 = runCompatibleQueryRep $ BelongsTo a1 a2

-- | The lifted version of 'Database.Persist.Sql.belongsToJust'
belongsToJust
  :: (PersistEntity record1, PersistRecordBackend record2 SqlBackend, Typeable record1, Typeable record2, MonadSqlQuery m)
  => (record1 -> Key record2) -> record1 -> m record2
belongsToJust a1 a2 = runCompatibleQueryRep $ BelongsToJust a1 a2

-- | The lifted version of 'Database.Persist.Sql.insert'
insert
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Key record)
insert a1 = runCompatibleQueryRep $ Insert a1

-- | The lifted version of 'Database.Persist.Sql.insert_'
insert_
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m ()
insert_ a1 = runCompatibleQueryRep $ Insert_ a1

-- | The lifted version of 'Database.Persist.Sql.insertMany'
insertMany
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [record] -> m [Key record]
insertMany a1 = runCompatibleQueryRep $ InsertMany a1

-- | The lifted version of 'Database.Persist.Sql.insertMany_'
insertMany_
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [record] -> m ()
insertMany_ a1 = runCompatibleQueryRep $ InsertMany_ a1

-- | The lifted version of 'Database.Persist.Sql.insertEntityMany'
insertEntityMany
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Entity record] -> m ()
insertEntityMany a1 = runCompatibleQueryRep $ InsertEntityMany a1

-- | The lifted version of 'Database.Persist.Sql.insertKey'
insertKey
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> record -> m ()
insertKey a1 a2 = runCompatibleQueryRep $ InsertKey a1 a2

-- | The lifted version of 'Database.Persist.Sql.repsert'
repsert
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> record -> m ()
repsert a1 a2 = runCompatibleQueryRep $ Repsert a1 a2

-- | The lifted version of 'Database.Persist.Sql.repsertMany'
repsertMany
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [(Key record, record)] -> m ()
repsertMany a1 = runCompatibleQueryRep $ RepsertMany a1

-- | The lifted version of 'Database.Persist.Sql.replace'
replace
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> record -> m ()
replace a1 a2 = runCompatibleQueryRep $ Replace a1 a2

-- | The lifted version of 'Database.Persist.Sql.delete'
delete
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> m ()
delete a1 = runCompatibleQueryRep $ Delete a1

-- | The lifted version of 'Database.Persist.Sql.update'
update
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> [Update record] -> m ()
update a1 a2 = runCompatibleQueryRep $ Update a1 a2

-- | The lifted version of 'Database.Persist.Sql.updateGet'
updateGet
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> [Update record] -> m record
updateGet a1 a2 = runCompatibleQueryRep $ UpdateGet a1 a2

-- | The lifted version of 'Database.Persist.Sql.insertEntity'
insertEntity
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Entity record)
insertEntity a1 = runCompatibleQueryRep $ InsertEntity a1

-- | The lifted version of 'Database.Persist.Sql.insertRecord'
insertRecord
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m record
insertRecord a1 = runCompatibleQueryRep $ InsertRecord a1

-- | The lifted version of 'Database.Persist.Sql.getBy'
getBy
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Unique record -> m (Maybe (Entity record))
getBy a1 = runCompatibleQueryRep $ GetBy a1

#if MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.getByValue'
getByValue
  :: (PersistRecordBackend record SqlBackend, AtLeastOneUniqueKey record, Typeable record, MonadSqlQuery m)
  => record -> m (Maybe (Entity record))
getByValue a1 = runCompatibleQueryRep $ GetByValue a1
#endif

#if !MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.getByValue'
getByValue
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Maybe (Entity record))
getByValue a1 = runCompatibleQueryRep $ GetByValue a1
#endif

-- | The lifted version of 'Database.Persist.Sql.checkUnique'
checkUnique
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Maybe (Unique record))
checkUnique a1 = runCompatibleQueryRep $ CheckUnique a1

#if MIN_VERSION_persistent(2,11,0)
-- | The lifted version of 'Database.Persist.Sql.checkUniqueUpdateable'
checkUniqueUpdateable
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Entity record -> m (Maybe (Unique record))
checkUniqueUpdateable a1 = runCompatibleQueryRep $ CheckUniqueUpdateable a1
#endif

-- | The lifted version of 'Database.Persist.Sql.deleteBy'
deleteBy
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Unique record -> m ()
deleteBy a1 = runCompatibleQueryRep $ DeleteBy a1

-- | The lifted version of 'Database.Persist.Sql.insertUnique'
insertUnique
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Maybe (Key record))
insertUnique a1 = runCompatibleQueryRep $ InsertUnique a1

#if MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.upsert'
upsert
  :: (PersistRecordBackend record SqlBackend, OnlyOneUniqueKey record, Typeable record, MonadSqlQuery m)
  => record -> [Update record] -> m (Entity record)
upsert a1 a2 = runCompatibleQueryRep $ Upsert a1 a2
#endif

#if !MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.upsert'
upsert
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> [Update record] -> m (Entity record)
upsert a1 a2 = runCompatibleQueryRep $ Upsert a1 a2
#endif

-- | The lifted version of 'Database.Persist.Sql.upsertBy'
upsertBy
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => Unique record -> record -> [Update record] -> m (Entity record)
upsertBy a1 a2 a3 = runCompatibleQueryRep $ UpsertBy a1 a2 a3

-- | The lifted version of 'Database.Persist.Sql.putMany'
putMany
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [record] -> m ()
putMany a1 = runCompatibleQueryRep $ PutMany a1

#if MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.insertBy'
insertBy
  :: (PersistRecordBackend record SqlBackend, AtLeastOneUniqueKey record, Typeable record, MonadSqlQuery m)
  => record -> m (Either (Entity record) (Key record))
insertBy a1 = runCompatibleQueryRep $ InsertBy a1
#endif

#if !MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.insertBy'
insertBy
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Either (Entity record) (Key record))
insertBy a1 = runCompatibleQueryRep $ InsertBy a1
#endif

-- | The lifted version of 'Database.Persist.Sql.insertUniqueEntity'
insertUniqueEntity
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Maybe (Entity record))
insertUniqueEntity a1 = runCompatibleQueryRep $ InsertUniqueEntity a1

-- | The lifted version of 'Database.Persist.Sql.replaceUnique'
replaceUnique
  :: (PersistRecordBackend record SqlBackend, Eq (Unique record), Eq record, Typeable record, MonadSqlQuery m)
  => Key record -> record -> m (Maybe (Unique record))
replaceUnique a1 a2 = runCompatibleQueryRep $ ReplaceUnique a1 a2

#if MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.onlyUnique'
onlyUnique
  :: (PersistRecordBackend record SqlBackend, OnlyOneUniqueKey record, Typeable record, MonadSqlQuery m)
  => record -> m (Unique record)
onlyUnique a1 = runCompatibleQueryRep $ OnlyUnique a1
#endif

#if !MIN_VERSION_persistent(2,10,0)
-- | The lifted version of 'Database.Persist.Sql.onlyUnique'
onlyUnique
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m (Unique record)
onlyUnique a1 = runCompatibleQueryRep $ OnlyUnique a1
#endif

-- | The lifted version of 'Database.Persist.Sql.selectSourceRes'
selectSourceRes
  :: (MonadIO m2, PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> m (Acquire (ConduitM () (Entity record) m2 ()))
selectSourceRes a1 a2 = runCompatibleQueryRep $ SelectSourceRes a1 a2

-- | The lifted version of 'Database.Persist.Sql.selectFirst'
selectFirst
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> m (Maybe (Entity record))
selectFirst a1 a2 = runCompatibleQueryRep $ SelectFirst a1 a2

-- | The lifted version of 'Database.Persist.Sql.selectKeysRes'
selectKeysRes
  :: (MonadIO m2, PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> m (Acquire (ConduitM () (Key record) m2 ()))
selectKeysRes a1 a2 = runCompatibleQueryRep $ SelectKeysRes a1 a2

-- | The lifted version of 'Database.Persist.Sql.count'
count
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> m Int
count a1 = runCompatibleQueryRep $ Count a1

#if MIN_VERSION_persistent(2,11,0)
-- | The lifted version of 'Database.Persist.Sql.exists'
exists
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> m Bool
exists a1 = runCompatibleQueryRep $ Exists a1
#endif

-- | The lifted version of 'Database.Persist.Sql.selectSource'
selectSource
  :: (PersistRecordBackend record SqlBackend, MonadResource m, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> ConduitM () (Entity record) m ()
selectSource a1 a2 = fromAcquire $ runCompatibleQueryRep $ SelectSourceRes a1 a2

-- | The lifted version of 'Database.Persist.Sql.selectKeys'
selectKeys
  :: (PersistRecordBackend record SqlBackend, MonadResource m, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> ConduitM () (Key record) m ()
selectKeys a1 a2 = fromAcquire $ runCompatibleQueryRep $ SelectKeysRes a1 a2

-- | The lifted version of 'Database.Persist.Sql.selectList'
selectList
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> m [Entity record]
selectList a1 a2 = runCompatibleQueryRep $ SelectList a1 a2

-- | The lifted version of 'Database.Persist.Sql.selectKeysList'
selectKeysList
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [SelectOpt record] -> m [Key record]
selectKeysList a1 a2 = runCompatibleQueryRep $ SelectKeysList a1 a2

-- | The lifted version of 'Database.Persist.Sql.updateWhere'
updateWhere
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [Update record] -> m ()
updateWhere a1 a2 = runCompatibleQueryRep $ UpdateWhere a1 a2

-- | The lifted version of 'Database.Persist.Sql.deleteWhere'
deleteWhere
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> m ()
deleteWhere a1 = runCompatibleQueryRep $ DeleteWhere a1

-- | The lifted version of 'Database.Persist.Sql.deleteWhereCount'
deleteWhereCount
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> m Int64
deleteWhereCount a1 = runCompatibleQueryRep $ DeleteWhereCount a1

-- | The lifted version of 'Database.Persist.Sql.updateWhereCount'
updateWhereCount
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> [Update record] -> m Int64
updateWhereCount a1 a2 = runCompatibleQueryRep $ UpdateWhereCount a1 a2

#if !MIN_VERSION_persistent(2,13,0)
-- | The lifted version of 'Database.Persist.Sql.deleteCascade'
deleteCascade
  :: (DeleteCascade record SqlBackend, Typeable record, MonadSqlQuery m)
  => Key record -> m ()
deleteCascade a1 = runCompatibleQueryRep $ DeleteCascade a1
#endif

#if !MIN_VERSION_persistent(2,13,0)
-- | The lifted version of 'Database.Persist.Sql.deleteCascadeWhere'
deleteCascadeWhere
  :: (DeleteCascade record SqlBackend, Typeable record, MonadSqlQuery m)
  => [Filter record] -> m ()
deleteCascadeWhere a1 = runCompatibleQueryRep $ DeleteCascadeWhere a1
#endif

-- | The lifted version of 'Database.Persist.Sql.parseMigration'
parseMigration
  :: (HasCallStack, MonadSqlQuery m)
  => Migration -> m (Either [Text] CautiousMigration)
parseMigration a1 = runCompatibleQueryRep $ ParseMigration a1

-- | The lifted version of 'Database.Persist.Sql.parseMigration''
parseMigration'
  :: (HasCallStack, MonadSqlQuery m)
  => Migration -> m CautiousMigration
parseMigration' a1 = runCompatibleQueryRep $ ParseMigration' a1

-- | The lifted version of 'Database.Persist.Sql.printMigration'
printMigration
  :: (HasCallStack, MonadSqlQuery m)
  => Migration -> m ()
printMigration a1 = runCompatibleQueryRep $ PrintMigration a1

-- | The lifted version of 'Database.Persist.Sql.showMigration'
showMigration
  :: (HasCallStack, MonadSqlQuery m)
  => Migration -> m [Text]
showMigration a1 = runCompatibleQueryRep $ ShowMigration a1

-- | The lifted version of 'Database.Persist.Sql.getMigration'
getMigration
  :: (HasCallStack, MonadSqlQuery m)
  => Migration -> m [Sql]
getMigration a1 = runCompatibleQueryRep $ GetMigration a1

-- | The lifted version of 'Database.Persist.Sql.runMigration'
runMigration
  :: (MonadSqlQuery m)
  => Migration -> m ()
runMigration a1 = runCompatibleQueryRep $ RunMigration a1

#if MIN_VERSION_persistent(2,10,2)
-- | The lifted version of 'Database.Persist.Sql.runMigrationQuiet'
runMigrationQuiet
  :: (MonadSqlQuery m)
  => Migration -> m [Text]
runMigrationQuiet a1 = runCompatibleQueryRep $ RunMigrationQuiet a1
#endif

-- | The lifted version of 'Database.Persist.Sql.runMigrationSilent'
runMigrationSilent
  :: (MonadSqlQuery m)
  => Migration -> m [Text]
runMigrationSilent a1 = runCompatibleQueryRep $ RunMigrationSilent a1

-- | The lifted version of 'Database.Persist.Sql.runMigrationUnsafe'
runMigrationUnsafe
  :: (MonadSqlQuery m)
  => Migration -> m ()
runMigrationUnsafe a1 = runCompatibleQueryRep $ RunMigrationUnsafe a1

#if MIN_VERSION_persistent(2,10,2)
-- | The lifted version of 'Database.Persist.Sql.runMigrationUnsafeQuiet'
runMigrationUnsafeQuiet
  :: (HasCallStack, MonadSqlQuery m)
  => Migration -> m [Text]
runMigrationUnsafeQuiet a1 = runCompatibleQueryRep $ RunMigrationUnsafeQuiet a1
#endif

-- | The lifted version of 'Database.Persist.Sql.getFieldName'
getFieldName
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => EntityField record typ -> m Text
getFieldName a1 = runCompatibleQueryRep $ GetFieldName a1

-- | The lifted version of 'Database.Persist.Sql.getTableName'
getTableName
  :: (PersistRecordBackend record SqlBackend, Typeable record, MonadSqlQuery m)
  => record -> m Text
getTableName a1 = runCompatibleQueryRep $ GetTableName a1

-- | The lifted version of 'Database.Persist.Sql.withRawQuery'
withRawQuery
  :: (MonadSqlQuery m)
  => Text -> [PersistValue] -> ConduitM [PersistValue] Void IO a -> m a
withRawQuery a1 a2 a3 = runCompatibleQueryRep $ WithRawQuery a1 a2 a3

-- | The lifted version of 'Database.Persist.Sql.rawQueryRes'
rawQueryRes
  :: (MonadIO m2, MonadSqlQuery m)
  => Text -> [PersistValue] -> m (Acquire (ConduitM () [PersistValue] m2 ()))
rawQueryRes a1 a2 = runCompatibleQueryRep $ RawQueryRes a1 a2

-- | The lifted version of 'Database.Persist.Sql.rawQuery'
rawQuery
  :: (MonadResource m, MonadSqlQuery m)
  => Text -> [PersistValue] -> ConduitM () [PersistValue] m ()
rawQuery a1 a2 = fromAcquire $ runCompatibleQueryRep $ RawQueryRes a1 a2

-- | The lifted version of 'Database.Persist.Sql.rawExecute'
rawExecute
  :: (MonadSqlQuery m)
  => Text -> [PersistValue] -> m ()
rawExecute a1 a2 = runCompatibleQueryRep $ RawExecute a1 a2

-- | The lifted version of 'Database.Persist.Sql.rawExecuteCount'
rawExecuteCount
  :: (MonadSqlQuery m)
  => Text -> [PersistValue] -> m Int64
rawExecuteCount a1 a2 = runCompatibleQueryRep $ RawExecuteCount a1 a2

-- | The lifted version of 'Database.Persist.Sql.rawSql'
rawSql
  :: (RawSql a, MonadSqlQuery m)
  => Text -> [PersistValue] -> m [a]
rawSql a1 a2 = runCompatibleQueryRep $ RawSql a1 a2

-- | The lifted version of 'Database.Persist.Sql.transactionSave'
transactionSave
  :: (MonadSqlQuery m)
  => m ()
transactionSave = runCompatibleQueryRep $ TransactionSave

#if MIN_VERSION_persistent(2,9,0)
-- | The lifted version of 'Database.Persist.Sql.transactionSaveWithIsolation'
transactionSaveWithIsolation
  :: (MonadSqlQuery m)
  => IsolationLevel -> m ()
transactionSaveWithIsolation a1 = runCompatibleQueryRep $ TransactionSaveWithIsolation a1
#endif

-- | The lifted version of 'Database.Persist.Sql.transactionUndo'
transactionUndo
  :: (MonadSqlQuery m)
  => m ()
transactionUndo = runCompatibleQueryRep $ TransactionUndo

#if MIN_VERSION_persistent(2,9,0)
-- | The lifted version of 'Database.Persist.Sql.transactionUndoWithIsolation'
transactionUndoWithIsolation
  :: (MonadSqlQuery m)
  => IsolationLevel -> m ()
transactionUndoWithIsolation a1 = runCompatibleQueryRep $ TransactionUndoWithIsolation a1
#endif

-- | Lift an arbitrary 'SqlPersistT' action into 'MonadSqlQuery'.
--
-- This is unsafe because the action may be rerun. This function should
-- primarily be used to interop with other libraries built on top of
-- persistent.
--
-- Example usage:
--
-- @
-- -- | Run an esqueleto select.
-- select :: (MonadSqlQuery m, E.SqlSelect a r) => E.SqlQuery a -> m [r]
-- select q = unsafeLiftSql "esqueleto-select" (E.select q)
-- @
unsafeLiftSql :: MonadSqlQuery m => Text -> (forall m2. MonadIO m2 => SqlPersistT m2 a) -> m a
unsafeLiftSql label action = runCompatibleQueryRep $ UnsafeLiftSql label action

{- Helpers -}

-- | A helper for functions that return a conduit.
fromAcquire :: MonadResource m => m (Acquire (ConduitM i o m a)) -> ConduitM i o m a
fromAcquire getAcquire = do
  (_, conduit) <- lift $ getAcquire >>= allocateAcquire
  conduit
