name: PR Review Comment
on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for raising your pull request.

            Reviewer: Please verify the following things have been done, if applicable.
            - [ ] Tests have been added
            - [ ] `CHANGELOG.md` has been updated
            - [ ] `README.md` has been updated
